package org.tidecloak.iga.replay;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jboss.logging.Logger;
import org.keycloak.connections.jpa.JpaConnectionProvider;
import org.keycloak.models.ClientModel;
import org.keycloak.models.ClientScopeModel;
import org.keycloak.models.GroupModel;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.RealmModel;
import org.keycloak.models.RoleModel;
import org.tidecloak.iga.entities.IgaChangeRequestEntity;

import jakarta.persistence.EntityManager;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Replays an approved IGA change request by invoking the real Keycloak model
 * operations with IGA_REPLAY_ACTIVE set, then writing the final attestation
 * onto the affected rows via JPQL UPDATE.
 *
 * <h2>rowsJson key contract (authoritative)</h2>
 * Every capture site and every replay site MUST follow this contract. There is
 * NO legacy/old-format fallback — pending change requests created under the old
 * (pre-contract) convention are intentionally discarded and will fail loudly on
 * replay rather than silently mis-resolve.
 *
 * <ul>
 *   <li>{@code ID} — the affected row's OWN primary key (UUID). Always.</li>
 *   <li>{@code REALM_ID} — realm UUID, where applicable.</li>
 *   <li>{@code CLIENT_UUID} — a <i>referenced</i> client's UUID
 *       (resolve via {@code session.clients().getClientById(realm, uuid)}).</li>
 *   <li>{@code CLIENT_ID} — a <i>referenced</i> client's HUMAN identifier
 *       (e.g. {@code my-app}). NEVER a UUID. This is the one explicit exception
 *       to the "{@code *_ID} keys hold a UUID" rule, and it exists because it
 *       matches Keycloak's {@code CLIENT.CLIENT_ID} column, which is the human
 *       client identifier.</li>
 *   <li>{@code CLIENT_SCOPE_ID} — a referenced client scope's UUID.</li>
 *   <li>{@code USER_ID}, {@code ROLE_ID}, {@code GROUP_ID} — referenced entity
 *       UUIDs. Rule: {@code *_ID} keys that reference another entity hold that
 *       entity's UUID, EXCEPT {@code CLIENT_ID} (see above).</li>
 *   <li>Human names: {@code USERNAME}, role {@code NAME}, group {@code NAME},
 *       scope {@code NAME} — unchanged.</li>
 *   <li>{@code REP_JSON} — for EVERY {@code CREATE_*} action
 *       ({@code CREATE_USER}, {@code CREATE_ROLE} realm+client,
 *       {@code CREATE_GROUP} top+child, {@code CREATE_CLIENT_SCOPE},
 *       {@code CREATE_CLIENT}) the full Keycloak representation captured by the
 *       JAX-RS request filter ({@code IgaRepresentationCaptureFilter}),
 *       serialized as a JSON string. Replay deserializes it to the matching
 *       representation, pins identity (own UUID via {@code ID}, plus the human
 *       identifier — username / role NAME / group NAME / scope NAME — and, for
 *       client roles, the owning client via {@code CLIENT_UUID}), and rebuilds
 *       the complete entity via Keycloak's own representation builder under
 *       {@code IGA_REPLAY_ACTIVE}. Absent ONLY for non-REST programmatic
 *       callers; replay then uses a minimal bare-create safety net. There is
 *       NO old-format compatibility — pending CRs created before this contract
 *       lack {@code REP_JSON} and are intentionally discarded; if such a CR is
 *       replayed it gets the bare safety net at most and never the full config
 *       (it does not silently mis-rebuild — it just under-rebuilds, by design,
 *       since old pending CRs are being discarded per prior user decision).</li>
 *   <li>{@code config} — (ADD_PROTOCOL_MAPPER / UPDATE_PROTOCOL_MAPPER) the
 *       full {@code ProtocolMapperModel} config map, serialized as a JSON
 *       object (same shape for both actions). Replay calls
 *       {@code ProtocolMapperModel.setConfig(...)} from it; absent → empty
 *       config (bare safety net for non-REST callers).</li>
 *   <li><b>Organizations</b> (KC 26.5.5 org SPI). The
 *       {@code OrganizationProvider} SPI cannot pin an org id on create (like
 *       role/group create), so {@code CREATE_ORGANIZATION} is keyed by name,
 *       not id:
 *       <ul>
 *         <li>{@code ORG_ID} — an existing organization's UUID
 *             (UPDATE/DELETE/member/idp actions).</li>
 *         <li>{@code ORG_NAME} — the organization name (CREATE_ORGANIZATION
 *             only; the id is generated by the provider on replay).</li>
 *         <li>{@code ORG_ALIAS}, {@code ORG_REDIRECT_URL} — create args
 *             (CREATE_ORGANIZATION).</li>
 *         <li>{@code USER_ID} — member user UUID (ADD_ORG_MEMBER /
 *             REMOVE_ORG_MEMBER).</li>
 *         <li>{@code INVITE_EMAIL}, {@code INVITE_FIRST_NAME},
 *             {@code INVITE_LAST_NAME} — invitee payload
 *             ({@code ORG_INVITE_MEMBER} and {@code ORG_RESEND_INVITE}).
 *             Captured at the {@code InvitationManager.create} SPI seam
 *             BEFORE any invitation entity / action token / e-mail. Both
 *             invite endpoints ({@code .../members/invite-user} and
 *             {@code .../members/invite-existing-user}) converge on
 *             {@code InvitationManager.create(org,email,firstName,lastName)}
 *             so the email/name triple alone reconstructs either; replay
 *             re-resolves an existing user by e-mail vs. a registration link
 *             exactly like KC's {@code inviteUser}. NOT a {@code REP_JSON}
 *             action (the invite endpoints are form-encoded, not a JSON
 *             representation the capture filter handles). The resend variant
 *             ({@code ORG_RESEND_INVITE}) carries the identical row shape and
 *             replays through the SAME {@code replayOrgInviteMember} body —
 *             the action type is the audit-/scope-relevant distinction set by
 *             {@link org.tidecloak.iga.providers.IgaInvitationManager} via
 *             request-URI sniffing of the in-flight admin call.</li>
 *         <li>{@code IDP_ALIAS} — identity-provider alias (ORG_ADD_IDP /
 *             ORG_REMOVE_IDP); resolved via
 *             {@code session.identityProviders().getByIdOrAlias}.</li>
 *         <li>{@code REP_JSON} — for {@code CREATE_ORGANIZATION} and
 *             {@code UPDATE_ORGANIZATION} the full
 *             {@code OrganizationRepresentation} captured by the JAX-RS filter
 *             (POST/PUT {realm}/organizations[/{id}]). Replay rebuilds via
 *             {@code RepresentationToModel.toModel(rep, model)} — the exact
 *             builder {@code OrganizationsResource.create} /
 *             {@code OrganizationResource.update} use — which also applies
 *             {@code setDomains} (KC 26.5.5 has no standalone org-domain
 *             endpoint, so domain changes ride inside the org rep).</li>
 *       </ul>
 *       NOTE: {@code OrganizationEntity}/{@code OrganizationDomainEntity} have
 *       NO {@code attestation} column, so org replays deliberately do NOT
 *       stamp one — governance is fully tracked by the IGA_CHANGE_REQUEST row
 *       + REP_JSON rebuild (the org does not exist / is unchanged until
 *       commit). This needs no tidecloak-override change and is consistent
 *       with the "nothing pre-exists until commit" create model.</li>
 * </ul>
 */
public class IgaReplayDispatcher {

    private static final Logger log = Logger.getLogger(IgaReplayDispatcher.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final TypeReference<List<Map<String, Object>>> LIST_MAP_REF =
            new TypeReference<List<Map<String, Object>>>() {};

    public static void replay(KeycloakSession session, IgaChangeRequestEntity cr, String finalAttestation) {
        session.setAttribute("IGA_REPLAY_ACTIVE", "true");
        try {
            doReplay(session, cr, finalAttestation);
        } finally {
            session.removeAttribute("IGA_REPLAY_ACTIVE");
        }
    }

    private static void doReplay(KeycloakSession session, IgaChangeRequestEntity cr, String finalAttestation) {
        RealmModel realm = session.realms().getRealm(cr.getRealmId());
        EntityManager em = getEm(session);

        List<Map<String, Object>> rows = parseRows(cr.getRowsJson());

        switch (cr.getActionType()) {
            case "CREATE_USER" -> replayCreateUser(session, realm, rows, finalAttestation, em);
            case "CREATE_ROLE" -> replayCreateRole(session, realm, rows, finalAttestation, em);
            case "CREATE_GROUP" -> replayCreateGroup(session, realm, rows, finalAttestation, em);
            case "CREATE_CLIENT" -> replayCreateClient(session, realm, rows, finalAttestation, em);
            case "ADD_PROTOCOL_MAPPER" -> replayAddProtocolMapper(session, realm, cr, rows, finalAttestation, em);
            case "GRANT_ROLES" -> replayRelationship(session, realm, rows, finalAttestation, em,
                    "UPDATE UserRoleMappingEntity e SET e.attestation = :sig WHERE e.user.id = :k1 AND e.roleId = :k2",
                    "USER_ID", "ROLE_ID",
                    r -> grantRoleDirect(session, realm, r));
            case "REVOKE_ROLES" -> replayRevoke(session, realm, rows, em,
                    r -> revokeRoleDirect(session, realm, r));
            case "JOIN_GROUPS" -> replayRelationship(session, realm, rows, finalAttestation, em,
                    "UPDATE UserGroupMembershipEntity e SET e.attestation = :sig WHERE e.user.id = :k1 AND e.groupId = :k2",
                    "USER", "GROUP",
                    r -> joinGroupDirect(session, realm, r));
            case "LEAVE_GROUPS" -> replayRevoke(session, realm, rows, em,
                    r -> leaveGroupDirect(session, realm, r));
            case "GROUP_GRANT_ROLES" -> replayRelationship(session, realm, rows, finalAttestation, em,
                    "UPDATE GroupRoleMappingEntity e SET e.attestation = :sig WHERE e.group.id = :k1 AND e.roleId = :k2",
                    "GROUP", "ROLE",
                    r -> groupGrantRoleDirect(session, realm, r));
            case "GROUP_REVOKE_ROLES" -> replayRevoke(session, realm, rows, em,
                    r -> groupRevokeRoleDirect(session, realm, r));
            case "ADD_COMPOSITE" -> replayRelationship(session, realm, rows, finalAttestation, em,
                    "UPDATE CompositeRoleEntity e SET e.attestation = :sig WHERE e.parentRole.id = :k1 AND e.childRole.id = :k2",
                    "COMPOSITE", "CHILD_ROLE",
                    r -> addCompositeDirect(session, realm, r));
            case "REMOVE_COMPOSITE" -> replayRevoke(session, realm, rows, em,
                    r -> removeCompositeDirect(session, realm, r));
            case "ASSIGN_SCOPE" -> replayRelationship(session, realm, rows, finalAttestation, em,
                    // e.clientId is the ClientScopeClientMappingEntity column
                    // holding the client's UUID, so the stamp key is CLIENT_UUID
                    // (contract), not the human CLIENT_ID.
                    "UPDATE ClientScopeClientMappingEntity e SET e.attestation = :sig WHERE e.clientId = :k1 AND e.clientScopeId = :k2",
                    "CLIENT_UUID", "SCOPE_ID",
                    r -> assignScopeDirect(session, realm, r));
            case "REMOVE_SCOPE" -> replayRevoke(session, realm, rows, em,
                    r -> removeScopeDirect(session, realm, r));
            case "SCOPE_ADD_ROLE" -> replayRelationship(session, realm, rows, finalAttestation, em,
                    "UPDATE ClientScopeRoleMappingEntity e SET e.attestation = :sig WHERE e.clientScope.id = :k1 AND e.role.id = :k2",
                    "SCOPE_ID", "ROLE_ID",
                    r -> scopeAddRoleDirect(session, realm, r));
            case "SCOPE_REMOVE_ROLE" -> replayRevoke(session, realm, rows, em,
                    r -> scopeRemoveRoleDirect(session, realm, r));
            case "REQUEST_SERVER_CERT" -> replayRequestServerCert(cr);
            case "INSTALL_LICENSE", "ROTATE_LICENSE" -> replayLicenseAction(cr);

            // ----- Attribute writes -----
            case "SET_USER_ATTRIBUTE" -> replaySetUserAttribute(session, realm, rows, finalAttestation, em);
            case "REMOVE_USER_ATTRIBUTE" -> replayRemoveUserAttribute(session, realm, rows, em);
            case "SET_CLIENT_ATTRIBUTE" -> replaySetClientAttribute(session, realm, rows, finalAttestation, em);
            case "REMOVE_CLIENT_ATTRIBUTE" -> replayRemoveClientAttribute(session, realm, rows, em);
            case "SET_CLIENT_SCOPE_ATTRIBUTE" -> replaySetClientScopeAttribute(session, realm, rows, finalAttestation, em);
            case "REMOVE_CLIENT_SCOPE_ATTRIBUTE" -> replayRemoveClientScopeAttribute(session, realm, rows, em);
            case "SET_GROUP_ATTRIBUTE" -> replaySetGroupAttribute(session, realm, rows, finalAttestation, em);
            case "REMOVE_GROUP_ATTRIBUTE" -> replayRemoveGroupAttribute(session, realm, rows, em);
            case "SET_ROLE_ATTRIBUTE" -> replaySetRoleAttribute(session, realm, rows, finalAttestation, em);
            case "REMOVE_ROLE_ATTRIBUTE" -> replayRemoveRoleAttribute(session, realm, rows, em);
            case "SET_REALM_ATTRIBUTE" -> replaySetRealmAttribute(session, realm, rows, finalAttestation, em);
            case "REMOVE_REALM_ATTRIBUTE" -> replayRemoveRealmAttribute(session, realm, rows, em);

            // ----- Realm column / structural writes -----
            case "SET_REALM_CONFIG" -> replaySetRealmConfig(session, realm, rows);
            case "UPDATE_CLIENT_WEB_ORIGINS" -> replayUpdateClientWebOrigins(session, realm, rows);
            case "UPDATE_CLIENT_REDIRECT_URIS" -> replayUpdateClientRedirectUris(session, realm, rows);
            case "ADD_REALM_DEFAULT_GROUP" -> replayAddRealmDefaultGroup(session, realm, rows);
            case "REMOVE_REALM_DEFAULT_GROUP" -> replayRemoveRealmDefaultGroup(session, realm, rows);
            case "CREATE_CLIENT_SCOPE" -> replayCreateClientScope(session, realm, rows, finalAttestation, em);
            case "UPDATE_PROTOCOL_MAPPER" -> replayUpdateProtocolMapper(session, realm, rows, finalAttestation, em);
            case "REMOVE_PROTOCOL_MAPPER" -> replayRemoveProtocolMapper(session, realm, rows);

            // ----- Organizations (KC 26.5.5 org SPI) -----
            case "CREATE_ORGANIZATION" -> replayCreateOrganization(session, realm, rows);
            case "UPDATE_ORGANIZATION" -> replayUpdateOrganization(session, realm, rows);
            case "DELETE_ORGANIZATION" -> replayDeleteOrganization(session, realm, rows);
            case "ADD_ORG_MEMBER" -> replayAddOrgMember(session, realm, rows);
            case "REMOVE_ORG_MEMBER" -> replayRemoveOrgMember(session, realm, rows);
            case "ORG_INVITE_MEMBER", "ORG_RESEND_INVITE" -> replayOrgInviteMember(session, realm, rows);
            case "ORG_ADD_IDP" -> replayOrgAddIdp(session, realm, rows);
            case "ORG_REMOVE_IDP" -> replayOrgRemoveIdp(session, realm, rows);

            default -> throw new IllegalArgumentException("Unknown IGA action: " + cr.getActionType());
        }

        // Mark approved
        IgaChangeRequestEntity managed = em.find(IgaChangeRequestEntity.class, cr.getId());
        if (managed != null) {
            managed.setStatus("APPROVED");
            managed.setResolvedAt(System.currentTimeMillis());
        }
    }

    // -------------------------------------------------------------------------
    // CREATE replays
    // -------------------------------------------------------------------------

    private static void replayCreateUser(KeycloakSession session, RealmModel realm,
                                          List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String userId = str(row, "ID");
            String username = str(row, "USERNAME");
            String repJson = str(row, "REP_JSON");

            if (repJson != null && !repJson.isEmpty()) {
                // Full-config path: rebuild the complete user from the captured
                // UserRepresentation via the SAME builder Keycloak's import
                // path uses. RepresentationToModel.createUser delegates to
                // DefaultExportImportManager.createUser, which honours
                // rep.getId() (via the 5-arg local-storage addUser, NOT the
                // IGA-wrapped 1-arg addUser) and then applies enabled, email,
                // names, attributes, required actions, credentials (plaintext
                // value AND hashed secret/credential data), federated
                // identities, role mappings, client consents, notBefore,
                // service-account client link, and group memberships.
                // IGA_REPLAY_ACTIVE (set by replay()) makes every nested
                // IgaUserAdapter call (setEnabled/setAttribute/grantRole/
                // joinGroup/...) pass straight through the wrappers without
                // re-triggering interception.
                try {
                    org.keycloak.representations.idm.UserRepresentation rep =
                            MAPPER.readValue(repJson,
                                    org.keycloak.representations.idm.UserRepresentation.class);
                    // Pin identity to the captured values so the replayed user
                    // keeps the original UUID and username.
                    rep.setId(userId);
                    if (username != null) rep.setUsername(username);
                    org.keycloak.models.utils.RepresentationToModel.createUser(session, realm, rep);
                } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
                    throw new RuntimeException(
                            "Failed to deserialize REP_JSON for CREATE_USER replay (CR row id=" + userId + ")", e);
                }
            } else {
                // Bare-create safety net for non-REST programmatic callers
                // only (no REP_JSON). NOT a legacy-CR compat shim — an
                // admin-created user always carries REP_JSON. 5-arg addUser to
                // supply our own id.
                session.users().addUser(realm, userId, username, false, false);
            }
            em.createQuery("UPDATE UserEntity e SET e.attestation = :sig WHERE e.id = :id")
                    .setParameter("sig", sig)
                    .setParameter("id", userId)
                    .executeUpdate();
        }
    }

    private static void replayCreateRole(KeycloakSession session, RealmModel realm,
                                          List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String id = str(row, "ID");
            String name = str(row, "NAME");
            boolean clientRole = Boolean.TRUE.equals(row.get("CLIENT_ROLE"));
            String repJson = str(row, "REP_JSON");

            // Create the role with the captured UUID + name. For client roles
            // resolve the owning client via CLIENT_UUID (contract). The
            // id-bearing add* lands in IgaRealmProvider.addRealmRole /
            // addClientRole which, under IGA_REPLAY_ACTIVE (set by replay()),
            // delegates to super and does NOT re-intercept.
            RoleModel role;
            if (clientRole) {
                ClientModel client = resolveClient(session, realm, row);
                if (client == null) {
                    log.warnf("CREATE_ROLE replay: owning client not resolvable for client role id=%s; skipping", id);
                    continue;
                }
                role = session.roles().addClientRole(client, id, name);
            } else {
                role = session.roles().addRealmRole(realm, id, name);
            }
            if (role == null) continue;

            if (repJson != null && !repJson.isEmpty()) {
                // Full-config path: apply description, attributes and
                // composites exactly as Keycloak's RoleContainerResource
                // .createRole does (it cannot pin an id, so we do the
                // id-bearing add above and then replicate the rest of its
                // logic faithfully — no invented behaviour).
                try {
                    org.keycloak.representations.idm.RoleRepresentation rep =
                            MAPPER.readValue(repJson,
                                    org.keycloak.representations.idm.RoleRepresentation.class);
                    if (rep.getDescription() != null) role.setDescription(rep.getDescription());
                    if (rep.getAttributes() != null) {
                        for (Map.Entry<String, java.util.List<String>> attr : rep.getAttributes().entrySet()) {
                            role.setAttribute(attr.getKey(), attr.getValue());
                        }
                    }
                    if (Boolean.TRUE.equals(rep.isComposite()) && rep.getComposites() != null) {
                        org.keycloak.representations.idm.RoleRepresentation.Composites composites =
                                rep.getComposites();
                        java.util.Set<String> compositeRealmRoles = composites.getRealm();
                        if (compositeRealmRoles != null) {
                            for (String roleName : compositeRealmRoles) {
                                RoleModel realmRole = realm.getRole(roleName);
                                if (realmRole == null) {
                                    // Composite target not yet created (it may
                                    // be a separate pending CR). Keycloak's REST
                                    // path 404s here; we log and skip the single
                                    // composite link rather than abort the whole
                                    // role create.
                                    log.warnf("CREATE_ROLE replay: composite realm role '%s' not found for role id=%s; skipping that composite link", roleName, id);
                                    continue;
                                }
                                role.addCompositeRole(realmRole);
                            }
                        }
                        Map<String, java.util.List<String>> compositeClientRoles = composites.getClient();
                        if (compositeClientRoles != null) {
                            for (Map.Entry<String, java.util.List<String>> e : compositeClientRoles.entrySet()) {
                                ClientModel cClient = realm.getClientByClientId(e.getKey());
                                if (cClient == null) continue; // Keycloak: continue
                                for (String roleName : e.getValue()) {
                                    RoleModel clientRoleModel = cClient.getRole(roleName);
                                    if (clientRoleModel == null) {
                                        log.warnf("CREATE_ROLE replay: composite client role '%s' (client %s) not found for role id=%s; skipping that composite link", roleName, e.getKey(), id);
                                        continue;
                                    }
                                    role.addCompositeRole(clientRoleModel);
                                }
                            }
                        }
                    }
                } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
                    throw new RuntimeException(
                            "Failed to deserialize REP_JSON for CREATE_ROLE replay (CR row id=" + id + ")", e);
                }
            }
            // else: bare-create safety net (non-REST callers) — role already
            // created above with id+name; no extra config.

            em.createQuery("UPDATE RoleEntity e SET e.attestation = :sig WHERE e.id = :id")
                    .setParameter("sig", sig)
                    .setParameter("id", id)
                    .executeUpdate();
        }
    }

    private static void replayCreateGroup(KeycloakSession session, RealmModel realm,
                                           List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String id = str(row, "ID");
            String name = str(row, "NAME");
            String parentId = str(row, "PARENT_GROUP");
            String repJson = str(row, "REP_JSON");
            GroupModel parent = (parentId != null) ? session.groups().getGroupById(realm, parentId) : null;
            // Create with the captured UUID + name + (resolved) parent. This
            // lands in IgaRealmProvider.createGroup, which under
            // IGA_REPLAY_ACTIVE (set by replay()) delegates to super and does
            // NOT re-intercept. Top-level vs child is decided purely by whether
            // PARENT_GROUP was captured — matching Keycloak's
            // GroupsResource.addTopLevelGroup vs GroupResource.addChild.
            GroupModel group = session.groups().createGroup(realm, id, name, parent);

            if (group != null && repJson != null && !repJson.isEmpty()) {
                // Full-config path: apply description + attributes exactly as
                // Keycloak's GroupResource.updateGroup does after create. We do
                // NOT recurse into subGroups — Keycloak creates each sub-group
                // via its own POST .../children request (its own CREATE_GROUP
                // CR), so inventing recursion here would double-create.
                try {
                    org.keycloak.representations.idm.GroupRepresentation rep =
                            MAPPER.readValue(repJson,
                                    org.keycloak.representations.idm.GroupRepresentation.class);
                    if (rep.getAttributes() != null) {
                        for (Map.Entry<String, java.util.List<String>> attr : rep.getAttributes().entrySet()) {
                            group.setAttribute(attr.getKey(), attr.getValue());
                        }
                    }
                    // Keycloak's updateGroup always calls setDescription(rep
                    // .getDescription()) (including null) — mirror exactly.
                    group.setDescription(rep.getDescription());
                } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
                    throw new RuntimeException(
                            "Failed to deserialize REP_JSON for CREATE_GROUP replay (CR row id=" + id + ")", e);
                }
            }
            // else: bare-create safety net (non-REST callers).

            em.createQuery("UPDATE GroupEntity e SET e.attestation = :sig WHERE e.id = :id")
                    .setParameter("sig", sig)
                    .setParameter("id", id)
                    .executeUpdate();
        }
    }

    private static void replayCreateClient(KeycloakSession session, RealmModel realm,
                                            List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String id = str(row, "ID");
            // CLIENT_ID is the HUMAN client identifier (contract). The own PK
            // UUID is ID.
            String clientId = str(row, "CLIENT_ID");
            String repJson = str(row, "REP_JSON");

            if (repJson != null && !repJson.isEmpty()) {
                // Full-config path: rebuild the complete client from the
                // captured ClientRepresentation via the same builder Keycloak
                // uses on POST {realm}/clients. IGA_REPLAY_ACTIVE is set by the
                // surrounding replay() call, so RepresentationToModel.createClient's
                // internal realm.addClient(...) + setters + addProtocolMapper(...)
                // pass straight through the IGA wrappers without re-triggering
                // interception.
                try {
                    org.keycloak.representations.idm.ClientRepresentation rep =
                            MAPPER.readValue(repJson,
                                    org.keycloak.representations.idm.ClientRepresentation.class);
                    // Pin identity to the captured values so the replayed
                    // client keeps the original UUID (ID) and human clientId.
                    rep.setId(id);
                    if (clientId != null) rep.setClientId(clientId);
                    int wo = rep.getWebOrigins() == null ? 0 : rep.getWebOrigins().size();
                    int ru = rep.getRedirectUris() == null ? 0 : rep.getRedirectUris().size();
                    log.infof("IGA replay CREATE_CLIENT: full-rep path for clientId=%s "
                            + "(webOrigins=%d, redirectUris=%d) via RepresentationToModel.createClient",
                            clientId, wo, ru);
                    org.keycloak.models.utils.RepresentationToModel.createClient(session, realm, rep);
                } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
                    throw new RuntimeException(
                            "Failed to deserialize REP_JSON for CREATE_CLIENT replay (CR row id=" + id + ")", e);
                }
            } else {
                // Safety net for non-rep callers only (e.g. a programmatic
                // session.clients().addClient(...) that did NOT go through
                // RepresentationToModel.createClient — so the model-layer
                // capture seam never produced a REP_JSON). This is NOT a
                // legacy-CR compatibility shim: old pending CRs lacking
                // REP_JSON are intentionally discarded, and an admin-created
                // client always has REP_JSON (captured at the model-layer
                // terminal seam IgaClientAdapter#updateClient).
                log.warnf("IGA replay CREATE_CLIENT: REP_JSON MISSING for clientId=%s "
                        + "— bare client create only (webOrigins/redirectUris/attributes/flows "
                        + "WILL BE LOST). The model-layer capture seam did not record a full "
                        + "representation for this client create (non-REST programmatic caller).",
                        clientId);
                session.clients().addClient(realm, id, clientId != null ? clientId : id);
            }
            em.createQuery("UPDATE ClientEntity e SET e.attestation = :sig WHERE e.id = :id")
                    .setParameter("sig", sig)
                    .setParameter("id", id)
                    .executeUpdate();
        }
    }

    // -------------------------------------------------------------------------
    // Organizations (KC 26.5.5 org SPI)
    //
    // All calls run under IGA_REPLAY_ACTIVE (set by replay()), so
    // IgaOrganizationProvider.isIgaActive() returns false and every
    // session.getProvider(OrganizationProvider.class) call passes straight
    // through to JpaOrganizationProvider WITHOUT re-interception — exactly the
    // same non-reinterception contract as IgaRealmProvider/IgaUserAdapter.
    //
    // NOTE: OrganizationEntity / OrganizationDomainEntity have NO attestation
    // column (unlike the 19 tidecloak-override entities). Org governance is
    // tracked entirely by the IGA_CHANGE_REQUEST row + REP_JSON rebuild — the
    // org simply does not exist (or is unchanged) until commit — so there is
    // deliberately NO `UPDATE <orgEntity> SET attestation=...` stamp here and
    // no cross-repo schema change is required. See the report.
    // -------------------------------------------------------------------------

    private static org.keycloak.organization.OrganizationProvider orgProvider(KeycloakSession session) {
        return session.getProvider(org.keycloak.organization.OrganizationProvider.class);
    }

    private static void replayCreateOrganization(KeycloakSession session, RealmModel realm,
                                                  List<Map<String, Object>> rows) {
        org.keycloak.organization.OrganizationProvider orgs = orgProvider(session);
        for (Map<String, Object> row : rows) {
            String name = str(row, "ORG_NAME");
            String alias = str(row, "ORG_ALIAS");
            String repJson = str(row, "REP_JSON");
            // Mirror OrganizationsResource.create EXACTLY: provider.create(name,
            // alias) then RepresentationToModel.toModel(rep, model). The org id
            // is generated by JpaOrganizationProvider.create (the SPI cannot
            // pin an id — same constraint as role/group create). With
            // IGA_REPLAY_ACTIVE the wrapped create passes through to super.
            org.keycloak.models.OrganizationModel model = orgs.create(name, alias);
            if (model == null) {
                log.warnf("CREATE_ORGANIZATION replay: provider.create returned null for name=%s", name);
                continue;
            }
            if (repJson != null && !repJson.isEmpty()) {
                try {
                    org.keycloak.representations.idm.OrganizationRepresentation rep =
                            MAPPER.readValue(repJson,
                                    org.keycloak.representations.idm.OrganizationRepresentation.class);
                    // Pin name/alias to the captured create args; toModel
                    // applies enabled/description/redirectUrl/attributes/domains
                    // — the identical builder OrganizationsResource.create runs.
                    rep.setName(name);
                    if (alias != null) rep.setAlias(alias);
                    org.keycloak.models.utils.RepresentationToModel.toModel(rep, model);
                } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
                    throw new RuntimeException(
                            "Failed to deserialize REP_JSON for CREATE_ORGANIZATION replay (name="
                                    + name + ")", e);
                }
            }
            // No attestation stamp: org entities have no attestation column;
            // governance is the approved CR itself.
        }
    }

    private static void replayUpdateOrganization(KeycloakSession session, RealmModel realm,
                                                  List<Map<String, Object>> rows) {
        org.keycloak.organization.OrganizationProvider orgs = orgProvider(session);
        for (Map<String, Object> row : rows) {
            String orgId = str(row, "ORG_ID");
            String repJson = str(row, "REP_JSON");
            org.keycloak.models.OrganizationModel model = orgs.getById(orgId);
            if (model == null) {
                log.warnf("UPDATE_ORGANIZATION replay: org not found id=%s", orgId);
                continue;
            }
            if (repJson != null && !repJson.isEmpty()) {
                try {
                    org.keycloak.representations.idm.OrganizationRepresentation rep =
                            MAPPER.readValue(repJson,
                                    org.keycloak.representations.idm.OrganizationRepresentation.class);
                    // EXACTLY OrganizationResource.update: toModel(rep, model).
                    org.keycloak.models.utils.RepresentationToModel.toModel(rep, model);
                } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
                    throw new RuntimeException(
                            "Failed to deserialize REP_JSON for UPDATE_ORGANIZATION replay (orgId="
                                    + orgId + ")", e);
                }
            }
        }
    }

    private static void replayDeleteOrganization(KeycloakSession session, RealmModel realm,
                                                  List<Map<String, Object>> rows) {
        org.keycloak.organization.OrganizationProvider orgs = orgProvider(session);
        for (Map<String, Object> row : rows) {
            String orgId = str(row, "ORG_ID");
            org.keycloak.models.OrganizationModel model = orgs.getById(orgId);
            if (model == null) {
                log.warnf("DELETE_ORGANIZATION replay: org not found id=%s", orgId);
                continue;
            }
            orgs.remove(model);
        }
    }

    private static void replayAddOrgMember(KeycloakSession session, RealmModel realm,
                                           List<Map<String, Object>> rows) {
        org.keycloak.organization.OrganizationProvider orgs = orgProvider(session);
        for (Map<String, Object> row : rows) {
            String orgId = str(row, "ORG_ID");
            String userId = str(row, "USER_ID");
            org.keycloak.models.OrganizationModel model = orgs.getById(orgId);
            org.keycloak.models.UserModel user = session.users().getUserById(realm, userId);
            if (model == null || user == null) {
                log.warnf("ADD_ORG_MEMBER replay: org=%s user=%s unresolved", orgId, userId);
                continue;
            }
            orgs.addMember(model, user);
        }
    }

    private static void replayRemoveOrgMember(KeycloakSession session, RealmModel realm,
                                              List<Map<String, Object>> rows) {
        org.keycloak.organization.OrganizationProvider orgs = orgProvider(session);
        for (Map<String, Object> row : rows) {
            String orgId = str(row, "ORG_ID");
            String userId = str(row, "USER_ID");
            org.keycloak.models.OrganizationModel model = orgs.getById(orgId);
            org.keycloak.models.UserModel user = session.users().getUserById(realm, userId);
            if (model == null || user == null) {
                log.warnf("REMOVE_ORG_MEMBER replay: org=%s user=%s unresolved", orgId, userId);
                continue;
            }
            orgs.removeMember(model, user);
        }
    }

    /**
     * Replay an approved {@code ORG_INVITE_MEMBER}: NOW perform the real
     * Keycloak invitation (persist invitation, mint action token, send
     * e-mail). This is a faithful transcription of KC 26.5.5
     * {@code OrganizationInvitationResource.sendInvitation(UserModel)} (the
     * exact code reached from BOTH {@code POST .../members/invite-user} and
     * {@code .../invite-existing-user} — both converge on
     * {@code sendInvitation} → {@code invitationManager.create(org, email,
     * firstName, lastName)}). It reuses KC's own {@code InvitationManager},
     * {@code InviteOrgActionToken} and {@code EmailTemplateProvider
     * .sendOrgInviteEmail} — NO email templating / token logic is
     * reimplemented. The only line intentionally NOT reproduced is the
     * trailing {@code adminEvent.operation(ACTION)...success()} audit event:
     * it is not part of the invitation mechanics and the approved IGA change
     * request is itself the authoritative audit record (the dispatcher has no
     * AdminEventBuilder, exactly like every other replay action — threading
     * one through replay() would be a broad, fragile signature change for a
     * non-essential admin event).
     *
     * <p>Runs under {@code IGA_REPLAY_ACTIVE=true} (set by {@link #replay}),
     * so {@code IgaOrganizationProvider.getInvitationManager()} still returns
     * the {@link org.tidecloak.iga.providers.IgaInvitationManager} wrapper but
     * {@code isIgaActive()} is {@code false} → its {@code create()} passes
     * straight through to KC's {@code JpaInvitationManager}. No
     * re-interception, exactly the same non-reinterception contract as every
     * other org replay. {@code expiresAt} is computed inside KC's
     * {@code create()} as {@code Time.currentTime() +
     * realm.getActionTokenGeneratedByAdminLifespan()} — so token/invitation
     * validity correctly starts fresh at commit (approval) time, and the
     * serialized {@code InviteOrgActionToken} inherits that expiry. Replay
     * runs at most once per CR (commit rejects non-PENDING CRs and
     * {@code replay()} flips status to APPROVED), so exactly one
     * invitation/token/e-mail is produced — never a duplicate.</p>
     */
    private static void replayOrgInviteMember(KeycloakSession session, RealmModel realm,
                                              List<Map<String, Object>> rows) {
        org.keycloak.organization.OrganizationProvider orgs = orgProvider(session);
        for (Map<String, Object> row : rows) {
            String orgId = str(row, "ORG_ID");
            String email = str(row, "INVITE_EMAIL");
            String firstName = str(row, "INVITE_FIRST_NAME");
            String lastName = str(row, "INVITE_LAST_NAME");
            org.keycloak.models.OrganizationModel organization = orgs.getById(orgId);
            if (organization == null || email == null || email.isBlank()) {
                log.warnf("ORG_INVITE_MEMBER replay: org=%s email=%s unresolved", orgId, email);
                continue;
            }
            email = email.trim().toLowerCase();

            // Mirror OrganizationInvitationResource.inviteUser's existing-user
            // resolution: if a real user with this e-mail exists we invite the
            // existing user, otherwise a transient in-memory user drives the
            // registration link — exactly KC's branch in inviteUser ->
            // sendInvitation. (Both invite endpoints funnel here.)
            org.keycloak.models.UserModel user = session.users().getUserByEmail(realm, email);
            boolean existingUser = user != null;
            if (!existingUser) {
                org.keycloak.storage.adapter.InMemoryUserAdapter tmp =
                        new org.keycloak.storage.adapter.InMemoryUserAdapter(session, realm, null);
                tmp.setEmail(email);
                if (firstName != null && lastName != null) {
                    tmp.setFirstName(firstName);
                    tmp.setLastName(lastName);
                }
                user = tmp;
            }

            // === transcription of OrganizationInvitationResource.sendInvitation ===
            org.keycloak.organization.InvitationManager invitationManager = orgs.getInvitationManager();
            org.keycloak.models.OrganizationInvitationModel invitation = invitationManager.create(
                    organization, user.getEmail(), user.getFirstName(), user.getLastName());

            String link = user.getId() == null
                    ? createRegistrationLink(session, realm, organization, user, invitation)
                    : createInvitationLink(session, realm, organization, user, invitation);
            invitation.setInviteLink(link);

            try {
                long expMinutes = java.util.concurrent.TimeUnit.SECONDS.toMinutes(
                        realm.getActionTokenGeneratedByAdminLifespan());
                session.getProvider(org.keycloak.email.EmailTemplateProvider.class)
                        .setRealm(realm)
                        .setUser(user)
                        .sendOrgInviteEmail(organization, link, expMinutes);
            } catch (org.keycloak.email.EmailException e) {
                throw new RuntimeException(
                        "ORG_INVITE_MEMBER replay: failed to send invite e-mail (org=" + orgId
                                + ", email=" + email + ")", e);
            }
        }
    }

    // Link/token builders: verbatim transcription of the private helpers in
    // OrganizationInvitationResource (createInvitationLink / createRegistration
    // Link / createToken / resolveAccountClientBaseUrl) so the e-mailed link is
    // byte-for-byte what stock KC would have produced at request time.

    private static String createInvitationLink(KeycloakSession session, RealmModel realm,
                                                org.keycloak.models.OrganizationModel organization,
                                                org.keycloak.models.UserModel user,
                                                org.keycloak.models.OrganizationInvitationModel invitation) {
        return org.keycloak.services.resources.LoginActionsService
                .actionTokenProcessor(session.getContext().getUri())
                .queryParam("key", createInviteToken(session, realm, organization, user, invitation))
                .build(realm.getName()).toString();
    }

    private static String createRegistrationLink(KeycloakSession session, RealmModel realm,
                                                  org.keycloak.models.OrganizationModel organization,
                                                  org.keycloak.models.UserModel user,
                                                  org.keycloak.models.OrganizationInvitationModel invitation) {
        return org.keycloak.protocol.oidc.OIDCLoginProtocolService
                .registrationsUrl(session.getContext().getUri().getBaseUriBuilder())
                .queryParam(org.keycloak.OAuth2Constants.RESPONSE_TYPE,
                        org.keycloak.protocol.oidc.utils.OIDCResponseType.CODE)
                .queryParam(org.keycloak.models.Constants.CLIENT_ID,
                        org.keycloak.models.Constants.ACCOUNT_MANAGEMENT_CLIENT_ID)
                .queryParam(org.keycloak.models.Constants.TOKEN,
                        createInviteToken(session, realm, organization, user, invitation))
                .buildFromMap(Map.of("realm", realm.getName(), "protocol",
                        org.keycloak.protocol.oidc.OIDCLoginProtocol.LOGIN_PROTOCOL)).toString();
    }

    private static String createInviteToken(KeycloakSession session, RealmModel realm,
                                             org.keycloak.models.OrganizationModel organization,
                                             org.keycloak.models.UserModel user,
                                             org.keycloak.models.OrganizationInvitationModel invitation) {
        org.keycloak.authentication.actiontoken.inviteorg.InviteOrgActionToken token =
                new org.keycloak.authentication.actiontoken.inviteorg.InviteOrgActionToken(
                        user.getId(), invitation.getExpiresAt(), user.getEmail(),
                        org.keycloak.models.Constants.ACCOUNT_MANAGEMENT_CLIENT_ID);
        token.setOrgId(organization.getId());
        token.id(invitation.getId());
        if (organization.getRedirectUrl() == null || organization.getRedirectUrl().isBlank()) {
            token.setRedirectUri(resolveAccountClientBaseUrl(session, realm));
        } else {
            token.setRedirectUri(organization.getRedirectUrl());
        }
        return token.serialize(session, realm, session.getContext().getUri());
    }

    private static String resolveAccountClientBaseUrl(KeycloakSession session, RealmModel realm) {
        org.keycloak.models.ClientModel accountClient =
                realm.getClientByClientId(org.keycloak.models.Constants.ACCOUNT_MANAGEMENT_CLIENT_ID);
        if (accountClient != null) {
            String baseUrl = accountClient.getBaseUrl();
            if (baseUrl != null && !baseUrl.isBlank()) {
                return org.keycloak.services.util.ResolveRelative
                        .resolveRelativeUri(session, accountClient.getRootUrl(), baseUrl);
            }
        }
        return org.keycloak.services.Urls
                .accountBase(session.getContext().getUri().getBaseUri())
                .path("/").build(realm.getName()).toString();
    }

    private static void replayOrgAddIdp(KeycloakSession session, RealmModel realm,
                                        List<Map<String, Object>> rows) {
        org.keycloak.organization.OrganizationProvider orgs = orgProvider(session);
        for (Map<String, Object> row : rows) {
            String orgId = str(row, "ORG_ID");
            String idpAlias = str(row, "IDP_ALIAS");
            org.keycloak.models.OrganizationModel model = orgs.getById(orgId);
            org.keycloak.models.IdentityProviderModel idp =
                    session.identityProviders().getByIdOrAlias(idpAlias);
            if (model == null || idp == null) {
                log.warnf("ORG_ADD_IDP replay: org=%s idp=%s unresolved", orgId, idpAlias);
                continue;
            }
            orgs.addIdentityProvider(model, idp);
        }
    }

    private static void replayOrgRemoveIdp(KeycloakSession session, RealmModel realm,
                                           List<Map<String, Object>> rows) {
        org.keycloak.organization.OrganizationProvider orgs = orgProvider(session);
        for (Map<String, Object> row : rows) {
            String orgId = str(row, "ORG_ID");
            String idpAlias = str(row, "IDP_ALIAS");
            org.keycloak.models.OrganizationModel model = orgs.getById(orgId);
            org.keycloak.models.IdentityProviderModel idp =
                    session.identityProviders().getByIdOrAlias(idpAlias);
            if (model == null || idp == null) {
                log.warnf("ORG_REMOVE_IDP replay: org=%s idp=%s unresolved", orgId, idpAlias);
                continue;
            }
            orgs.removeIdentityProvider(model, idp);
        }
    }

    private static void replayAddProtocolMapper(KeycloakSession session, RealmModel realm,
                                                 IgaChangeRequestEntity cr, List<Map<String, Object>> rows,
                                                 String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String mapperId = str(row, "ID");
            // Parent may be a CLIENT (CLIENT_UUID, from IgaClientAdapter) or a
            // CLIENT_SCOPE (CLIENT_SCOPE_ID = scope UUID, from
            // IgaClientScopeAdapter). Client resolution goes through the
            // contract resolver (CLIENT_UUID → getClientById); a UUID is never
            // read out of CLIENT_ID.
            String clientUuid = str(row, "CLIENT_UUID");
            String clientId = str(row, "CLIENT_ID");
            String scopeId = str(row, "CLIENT_SCOPE_ID");
            org.keycloak.models.ProtocolMapperModel model = new org.keycloak.models.ProtocolMapperModel();
            model.setId(mapperId);
            model.setName(str(row, "NAME"));
            model.setProtocol(str(row, "PROTOCOL"));
            model.setProtocolMapper(str(row, "PROTOCOL_MAPPER_NAME"));
            // Apply the FULL captured config map (same shape/handling as
            // replayUpdateProtocolMapper). Absent → empty config (bare safety
            // net for non-REST callers / pre-contract pending CRs).
            Object cfg = row.get("config");
            if (cfg instanceof Map<?, ?> cfgMap) {
                java.util.Map<String, String> config = new java.util.LinkedHashMap<>();
                for (Map.Entry<?, ?> e : cfgMap.entrySet()) {
                    if (e.getKey() != null) {
                        config.put(e.getKey().toString(),
                                e.getValue() == null ? null : e.getValue().toString());
                    }
                }
                model.setConfig(config);
            } else {
                model.setConfig(new java.util.LinkedHashMap<>());
            }

            boolean added = false;
            if (clientUuid != null || clientId != null) {
                ClientModel client = resolveClient(session, realm, row);
                if (client != null) {
                    client.addProtocolMapper(model);
                    added = true;
                }
            } else if (scopeId != null) {
                ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
                if (scope != null) {
                    scope.addProtocolMapper(model);
                    added = true;
                }
            }

            if (added) {
                em.createQuery("UPDATE ProtocolMapperEntity e SET e.attestation = :sig WHERE e.id = :id")
                        .setParameter("sig", sig)
                        .setParameter("id", mapperId)
                        .executeUpdate();
            }
        }
    }

    // -------------------------------------------------------------------------
    // Server cert request — sidecar approval (no model write here)
    // -------------------------------------------------------------------------

    /**
     * REQUEST_SERVER_CERT approval grants the workload the right to receive a
     * cert. The sidecar IGA_SERVER_CERT_DRAFT is NOT touched here — issuance
     * is decoupled and happens via POST /iga/server-certs/{draftId}/issue once
     * the signing infrastructure produces the cert + trust bundle. The
     * surrounding doReplay() will mark the parent change request APPROVED.
     */
    private static void replayRequestServerCert(IgaChangeRequestEntity cr) {
        log.infof("REQUEST_SERVER_CERT approved for change request %s — awaiting cert issuance via /iga/server-certs/{draftId}/issue",
                cr.getId());
    }

    // -------------------------------------------------------------------------
    // License install/rotate — sidecar approval (no model write here)
    // -------------------------------------------------------------------------

    /**
     * INSTALL_LICENSE / ROTATE_LICENSE approval grants the realm permission to
     * install or rotate a license. The sidecar IGA_LICENSING_DRAFT is NOT
     * touched here — issuance is decoupled and happens via
     * POST /iga/licensing/drafts/{draftId}/issue once the licensing
     * infrastructure produces the signed license. The surrounding doReplay()
     * will mark the parent change request APPROVED.
     */
    private static void replayLicenseAction(IgaChangeRequestEntity cr) {
        log.infof("License action %s approved for change request %s — awaiting issuance via /iga/licensing/drafts/{draftId}/issue",
                cr.getActionType(), cr.getId());
    }

    // -------------------------------------------------------------------------
    // Relationship replays (add + write sig)
    // -------------------------------------------------------------------------

    private static void replayRelationship(KeycloakSession session, RealmModel realm,
                                            List<Map<String, Object>> rows, String sig, EntityManager em,
                                            String updateJpql, String rowKey1, String rowKey2,
                                            Consumer<Map<String, Object>> addOp) {
        for (Map<String, Object> row : rows) {
            addOp.accept(row);
        }
        // Stamp the attestation onto each row using the explicit row-key pair.
        if (sig == null || sig.isEmpty()) return;
        for (Map<String, Object> row : rows) {
            String k1 = str(row, rowKey1);
            String k2 = str(row, rowKey2);
            if (k1 == null || k2 == null) continue;
            em.createQuery(updateJpql)
                    .setParameter("sig", sig)
                    .setParameter("k1", k1)
                    .setParameter("k2", k2)
                    .executeUpdate();
        }
    }

    private static void replayRevoke(KeycloakSession session, RealmModel realm,
                                      List<Map<String, Object>> rows, EntityManager em,
                                      Consumer<Map<String, Object>> removeOp) {
        for (Map<String, Object> row : rows) {
            removeOp.accept(row);
        }
    }

    // -------------------------------------------------------------------------
    // Direct model operations (called with IGA_REPLAY_ACTIVE = true)
    // -------------------------------------------------------------------------

    private static void grantRoleDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String userId = str(row, "USER_ID");
        String roleId = str(row, "ROLE_ID");
        org.keycloak.models.UserModel user = session.users().getUserById(realm, userId);
        RoleModel role = session.roles().getRoleById(realm, roleId);
        if (user != null && role != null) user.grantRole(role);
    }

    private static void revokeRoleDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String userId = str(row, "USER_ID");
        String roleId = str(row, "ROLE_ID");
        org.keycloak.models.UserModel user = session.users().getUserById(realm, userId);
        RoleModel role = session.roles().getRoleById(realm, roleId);
        if (user != null && role != null) user.deleteRoleMapping(role);
    }

    private static void joinGroupDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String userId = str(row, "USER");
        String groupId = str(row, "GROUP");
        org.keycloak.models.UserModel user = session.users().getUserById(realm, userId);
        GroupModel group = session.groups().getGroupById(realm, groupId);
        if (user != null && group != null) user.joinGroup(group);
    }

    private static void leaveGroupDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String userId = str(row, "USER");
        String groupId = str(row, "GROUP");
        org.keycloak.models.UserModel user = session.users().getUserById(realm, userId);
        GroupModel group = session.groups().getGroupById(realm, groupId);
        if (user != null && group != null) user.leaveGroup(group);
    }

    private static void groupGrantRoleDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String groupId = str(row, "GROUP");
        String roleId = str(row, "ROLE");
        GroupModel group = session.groups().getGroupById(realm, groupId);
        RoleModel role = session.roles().getRoleById(realm, roleId);
        if (group != null && role != null) group.grantRole(role);
    }

    private static void groupRevokeRoleDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String groupId = str(row, "GROUP");
        String roleId = str(row, "ROLE");
        GroupModel group = session.groups().getGroupById(realm, groupId);
        RoleModel role = session.roles().getRoleById(realm, roleId);
        if (group != null && role != null) group.deleteRoleMapping(role);
    }

    private static void addCompositeDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String compositeId = str(row, "COMPOSITE");
        String childId = str(row, "CHILD_ROLE");
        RoleModel composite = session.roles().getRoleById(realm, compositeId);
        RoleModel child = session.roles().getRoleById(realm, childId);
        if (composite != null && child != null) composite.addCompositeRole(child);
    }

    private static void removeCompositeDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String compositeId = str(row, "COMPOSITE");
        String childId = str(row, "CHILD_ROLE");
        RoleModel composite = session.roles().getRoleById(realm, compositeId);
        RoleModel child = session.roles().getRoleById(realm, childId);
        if (composite != null && child != null) composite.removeCompositeRole(child);
    }

    private static void assignScopeDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String scopeId = str(row, "SCOPE_ID");
        boolean defaultScope = Boolean.TRUE.equals(row.get("DEFAULT_SCOPE"));
        ClientModel client = resolveClient(session, realm, row);
        ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
        if (client != null && scope != null) client.addClientScope(scope, defaultScope);
    }

    private static void removeScopeDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String scopeId = str(row, "SCOPE_ID");
        ClientModel client = resolveClient(session, realm, row);
        ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
        if (client != null && scope != null) client.removeClientScope(scope);
    }

    private static void scopeAddRoleDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String scopeId = str(row, "SCOPE_ID");
        String roleId = str(row, "ROLE_ID");
        ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
        RoleModel role = session.roles().getRoleById(realm, roleId);
        if (scope != null && role != null) scope.addScopeMapping(role);
    }

    private static void scopeRemoveRoleDirect(KeycloakSession session, RealmModel realm, Map<String, Object> row) {
        String scopeId = str(row, "SCOPE_ID");
        String roleId = str(row, "ROLE_ID");
        ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
        RoleModel role = session.roles().getRoleById(realm, roleId);
        if (scope != null && role != null) scope.deleteScopeMapping(role);
    }

    // -------------------------------------------------------------------------
    // Attribute replays.
    //
    // Approach: rebuild the attribute(s) by calling the underlying model's
    // setAttribute/removeAttribute (with IGA_REPLAY_ACTIVE = true so the IGA
    // wrappers pass straight through), then UPDATE the just-written rows with
    // the final attestation via JPQL. The attribute entities
    // (UserAttributeEntity / ClientAttributeEntity / ClientScopeAttributeEntity
    // / GroupAttributeEntity / RoleAttributeEntity / RealmAttributeEntity) all
    // declare an {@code attestation} field (see tidecloak-override).
    //
    // Multi-value SET requests carry one row per value. We group rows by
    // (parent_id, name) so the model write is a single setAttribute(name,
    // values) call, matching the original admin intent.
    // -------------------------------------------------------------------------

    private static java.util.Map<String, java.util.LinkedHashMap<String, java.util.List<String>>>
            groupByParentAndName(List<Map<String, Object>> rows, String parentKey) {
        java.util.Map<String, java.util.LinkedHashMap<String, java.util.List<String>>> out = new java.util.LinkedHashMap<>();
        for (Map<String, Object> row : rows) {
            String pid = str(row, parentKey);
            String name = str(row, "NAME");
            String value = str(row, "VALUE");
            if (pid == null || name == null) continue;
            out.computeIfAbsent(pid, k -> new java.util.LinkedHashMap<>())
                    .computeIfAbsent(name, k -> new java.util.ArrayList<>())
                    .add(value);
        }
        return out;
    }

    // ----- USER -----

    private static void replaySetUserAttribute(KeycloakSession session, RealmModel realm,
                                                List<Map<String, Object>> rows, String sig, EntityManager em) {
        var grouped = groupByParentAndName(rows, "USER_ID");
        for (var ue : grouped.entrySet()) {
            String userId = ue.getKey();
            org.keycloak.models.UserModel user = session.users().getUserById(realm, userId);
            if (user == null) continue;
            for (var ne : ue.getValue().entrySet()) {
                String name = ne.getKey();
                java.util.List<String> values = ne.getValue();
                user.setAttribute(name, values);
                stampSigJpql(em,
                        "UPDATE UserAttributeEntity e SET e.attestation = :sig " +
                                "WHERE e.user.id = :pid AND e.name = :name",
                        sig, userId, name);
            }
        }
    }

    private static void replayRemoveUserAttribute(KeycloakSession session, RealmModel realm,
                                                   List<Map<String, Object>> rows, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String userId = str(row, "USER_ID");
            String name = str(row, "NAME");
            org.keycloak.models.UserModel user = session.users().getUserById(realm, userId);
            if (user != null && name != null) user.removeAttribute(name);
        }
    }

    // ----- CLIENT -----

    private static void replaySetClientAttribute(KeycloakSession session, RealmModel realm,
                                                  List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String name = str(row, "NAME");
            String value = str(row, "VALUE");
            ClientModel client = resolveClient(session, realm, row);
            if (client == null || name == null) continue;
            client.setAttribute(name, value);
            stampSigJpql(em,
                    "UPDATE ClientAttributeEntity e SET e.attestation = :sig " +
                            "WHERE e.client.id = :pid AND e.name = :name",
                    sig, client.getId(), name);
        }
    }

    private static void replayRemoveClientAttribute(KeycloakSession session, RealmModel realm,
                                                     List<Map<String, Object>> rows, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String name = str(row, "NAME");
            ClientModel client = resolveClient(session, realm, row);
            if (client != null && name != null) client.removeAttribute(name);
        }
    }

    // ----- CLIENT_SCOPE -----

    private static void replaySetClientScopeAttribute(KeycloakSession session, RealmModel realm,
                                                       List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String scopeId = str(row, "SCOPE_ID");
            String name = str(row, "NAME");
            String value = str(row, "VALUE");
            ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
            if (scope == null || name == null) continue;
            scope.setAttribute(name, value);
            stampSigJpql(em,
                    "UPDATE ClientScopeAttributeEntity e SET e.attestation = :sig " +
                            "WHERE e.clientScope.id = :pid AND e.name = :name",
                    sig, scopeId, name);
        }
    }

    private static void replayRemoveClientScopeAttribute(KeycloakSession session, RealmModel realm,
                                                          List<Map<String, Object>> rows, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String scopeId = str(row, "SCOPE_ID");
            String name = str(row, "NAME");
            ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
            if (scope != null && name != null) scope.removeAttribute(name);
        }
    }

    // ----- GROUP -----

    private static void replaySetGroupAttribute(KeycloakSession session, RealmModel realm,
                                                 List<Map<String, Object>> rows, String sig, EntityManager em) {
        var grouped = groupByParentAndName(rows, "GROUP_ID");
        for (var ge : grouped.entrySet()) {
            String groupId = ge.getKey();
            GroupModel group = session.groups().getGroupById(realm, groupId);
            if (group == null) continue;
            for (var ne : ge.getValue().entrySet()) {
                String name = ne.getKey();
                java.util.List<String> values = ne.getValue();
                group.setAttribute(name, values);
                stampSigJpql(em,
                        "UPDATE GroupAttributeEntity e SET e.attestation = :sig " +
                                "WHERE e.group.id = :pid AND e.name = :name",
                        sig, groupId, name);
            }
        }
    }

    private static void replayRemoveGroupAttribute(KeycloakSession session, RealmModel realm,
                                                    List<Map<String, Object>> rows, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String groupId = str(row, "GROUP_ID");
            String name = str(row, "NAME");
            GroupModel group = session.groups().getGroupById(realm, groupId);
            if (group != null && name != null) group.removeAttribute(name);
        }
    }

    // ----- ROLE -----

    private static void replaySetRoleAttribute(KeycloakSession session, RealmModel realm,
                                                List<Map<String, Object>> rows, String sig, EntityManager em) {
        var grouped = groupByParentAndName(rows, "ROLE_ID");
        for (var re : grouped.entrySet()) {
            String roleId = re.getKey();
            RoleModel role = session.roles().getRoleById(realm, roleId);
            if (role == null) continue;
            for (var ne : re.getValue().entrySet()) {
                String name = ne.getKey();
                java.util.List<String> values = ne.getValue();
                role.setAttribute(name, values);
                stampSigJpql(em,
                        "UPDATE RoleAttributeEntity e SET e.attestation = :sig " +
                                "WHERE e.role.id = :pid AND e.name = :name",
                        sig, roleId, name);
            }
        }
    }

    private static void replayRemoveRoleAttribute(KeycloakSession session, RealmModel realm,
                                                   List<Map<String, Object>> rows, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String roleId = str(row, "ROLE_ID");
            String name = str(row, "NAME");
            RoleModel role = session.roles().getRoleById(realm, roleId);
            if (role != null && name != null) role.removeAttribute(name);
        }
    }

    // ----- REALM -----

    private static void replaySetRealmAttribute(KeycloakSession session, RealmModel realm,
                                                 List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String realmId = str(row, "REALM_ID");
            String name = str(row, "NAME");
            String value = str(row, "VALUE");
            RealmModel target = (realmId != null && realmId.equals(realm.getId()))
                    ? realm
                    : session.realms().getRealm(realmId);
            if (target == null || name == null) continue;
            target.setAttribute(name, value);
            stampSigJpql(em,
                    "UPDATE RealmAttributeEntity e SET e.attestation = :sig " +
                            "WHERE e.realm.id = :pid AND e.name = :name",
                    sig, realmId, name);
        }
    }

    private static void replayRemoveRealmAttribute(KeycloakSession session, RealmModel realm,
                                                    List<Map<String, Object>> rows, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String realmId = str(row, "REALM_ID");
            String name = str(row, "NAME");
            RealmModel target = (realmId != null && realmId.equals(realm.getId()))
                    ? realm
                    : session.realms().getRealm(realmId);
            if (target != null && name != null) target.removeAttribute(name);
        }
    }

    // -------------------------------------------------------------------------
    // Realm column / structural replays.
    //
    // These replay handlers re-invoke the underlying model setters with
    // IGA_REPLAY_ACTIVE = "true" so the IGA wrappers pass through. Where an
    // attestation can sensibly land on an entity we stamp it; for the
    // list-collection tables (web_origins, redirect_uris, realm_default_groups)
    // we accept that the change request itself is the audit record.
    // -------------------------------------------------------------------------

    private static void replaySetRealmConfig(KeycloakSession session, RealmModel realm,
                                              List<Map<String, Object>> rows) {
        for (Map<String, Object> row : rows) {
            String key = str(row, "key");
            String value = str(row, "value");
            if (key == null) continue;
            applyRealmConfig(session, realm, key, value);
        }
        // No per-attestation write — REALM has no ATTESTATION column. The CR
        // is the audit trail.
    }

    private static void applyRealmConfig(KeycloakSession session, RealmModel realm, String key, String value) {
        switch (key) {
            // Tier 1
            case "setEnabled" -> realm.setEnabled(parseBool(value));
            case "setSslRequired" -> {
                if (value != null) realm.setSslRequired(org.keycloak.common.enums.SslRequired.valueOf(value));
            }
            case "setPasswordPolicy" -> {
                if (value != null) realm.setPasswordPolicy(org.keycloak.models.PasswordPolicy.parse(session, value));
            }
            case "setOTPPolicy" -> realm.setOTPPolicy(parseOtpPolicy(value));
            case "setBruteForceProtected" -> realm.setBruteForceProtected(parseBool(value));
            case "setPermanentLockout" -> realm.setPermanentLockout(parseBool(value));
            case "setRegistrationAllowed" -> realm.setRegistrationAllowed(parseBool(value));
            case "setVerifyEmail" -> realm.setVerifyEmail(parseBool(value));
            case "setResetPasswordAllowed" -> realm.setResetPasswordAllowed(parseBool(value));
            case "setBrowserFlow" -> realm.setBrowserFlow(lookupFlow(realm, value));
            case "setDirectGrantFlow" -> realm.setDirectGrantFlow(lookupFlow(realm, value));
            case "setResetCredentialsFlow" -> realm.setResetCredentialsFlow(lookupFlow(realm, value));
            case "setClientAuthenticationFlow" -> realm.setClientAuthenticationFlow(lookupFlow(realm, value));
            case "setNotBefore" -> realm.setNotBefore(parseInt(value));
            // Tier 2
            case "setName" -> realm.setName(value);
            case "setRegistrationFlow" -> realm.setRegistrationFlow(lookupFlow(realm, value));
            case "setFirstBrokerLoginFlow" -> realm.setFirstBrokerLoginFlow(lookupFlow(realm, value));
            case "setRegistrationEmailAsUsername" -> realm.setRegistrationEmailAsUsername(parseBool(value));
            case "setEditUsernameAllowed" -> realm.setEditUsernameAllowed(parseBool(value));
            case "setLoginWithEmailAllowed" -> realm.setLoginWithEmailAllowed(parseBool(value));
            case "setDuplicateEmailsAllowed" -> realm.setDuplicateEmailsAllowed(parseBool(value));
            case "setRememberMe" -> realm.setRememberMe(parseBool(value));
            case "setFailureFactor" -> realm.setFailureFactor(parseInt(value));
            case "setMaxFailureWaitSeconds" -> realm.setMaxFailureWaitSeconds(parseInt(value));
            default -> log.warnf("SET_REALM_CONFIG replay: unknown setter '%s' — skipping", key);
        }
    }

    private static org.keycloak.models.AuthenticationFlowModel lookupFlow(RealmModel realm, String flowId) {
        if (flowId == null) return null;
        return realm.getAuthenticationFlowById(flowId);
    }

    private static org.keycloak.models.OTPPolicy parseOtpPolicy(String value) {
        if (value == null) return null;
        // Format: algorithm:digits:period:initialCounter:lookAheadWindow:type:reusable
        String[] parts = value.split(":", -1);
        if (parts.length < 7) {
            log.warnf("setOTPPolicy replay: malformed value '%s'", value);
            return null;
        }
        org.keycloak.models.OTPPolicy p = new org.keycloak.models.OTPPolicy();
        p.setAlgorithm(parts[0]);
        p.setDigits(Integer.parseInt(parts[1]));
        p.setPeriod(Integer.parseInt(parts[2]));
        p.setInitialCounter(Integer.parseInt(parts[3]));
        p.setLookAheadWindow(Integer.parseInt(parts[4]));
        p.setType(parts[5]);
        p.setCodeReusable(Boolean.parseBoolean(parts[6]));
        return p;
    }

    private static boolean parseBool(String v) {
        return Boolean.parseBoolean(v);
    }

    private static int parseInt(String v) {
        if (v == null) return 0;
        try { return Integer.parseInt(v); } catch (NumberFormatException e) { return 0; }
    }

    @SuppressWarnings("unchecked")
    private static java.util.List<String> strList(Object v) {
        if (v == null) return java.util.Collections.emptyList();
        if (v instanceof java.util.List<?> raw) {
            java.util.List<String> out = new java.util.ArrayList<>(raw.size());
            for (Object o : raw) out.add(o == null ? null : o.toString());
            return out;
        }
        return java.util.Collections.emptyList();
    }

    private static void replayUpdateClientWebOrigins(KeycloakSession session, RealmModel realm,
                                                      List<Map<String, Object>> rows) {
        for (Map<String, Object> row : rows) {
            ClientModel client = resolveClient(session, realm, row);
            if (client == null) continue;
            client.setWebOrigins(new java.util.LinkedHashSet<>(strList(row.get("values"))));
        }
    }

    private static void replayUpdateClientRedirectUris(KeycloakSession session, RealmModel realm,
                                                        List<Map<String, Object>> rows) {
        for (Map<String, Object> row : rows) {
            ClientModel client = resolveClient(session, realm, row);
            if (client == null) continue;
            client.setRedirectUris(new java.util.LinkedHashSet<>(strList(row.get("values"))));
        }
    }

    private static void replayAddRealmDefaultGroup(KeycloakSession session, RealmModel realm,
                                                    List<Map<String, Object>> rows) {
        for (Map<String, Object> row : rows) {
            String groupId = str(row, "GROUP_ID");
            if (groupId == null) continue;
            GroupModel group = session.groups().getGroupById(realm, groupId);
            if (group == null) continue;
            realm.addDefaultGroup(group);
        }
    }

    private static void replayRemoveRealmDefaultGroup(KeycloakSession session, RealmModel realm,
                                                       List<Map<String, Object>> rows) {
        for (Map<String, Object> row : rows) {
            String groupId = str(row, "GROUP_ID");
            if (groupId == null) continue;
            GroupModel group = session.groups().getGroupById(realm, groupId);
            if (group == null) continue;
            realm.removeDefaultGroup(group);
        }
    }

    /**
     * Replay CREATE_CLIENT_SCOPE: realm.addClientScope(id, name) plus optional
     * protocol/description, then stamp the attestation onto ClientScopeEntity
     * via JPQL. Requires the tidecloak-override commit that adds an
     * {@code attestation} field on {@code ClientScopeEntity}; without it this
     * UPDATE will fail at runtime.
     */
    private static void replayCreateClientScope(KeycloakSession session, RealmModel realm,
                                                  List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String id = str(row, "ID");
            String name = str(row, "NAME");
            String protocol = str(row, "PROTOCOL");
            String description = str(row, "DESCRIPTION");
            String repJson = str(row, "REP_JSON");
            if (id == null || name == null) continue;

            if (repJson != null && !repJson.isEmpty()) {
                // Full-config path: rebuild via the SAME builder Keycloak's
                // ClientScopesResource.create uses
                // (RepresentationToModel.createClientScope), which honours
                // rep.getId() (id-bearing realm.addClientScope) and applies
                // name, description, protocol, protocol mappers (incl. their
                // full config) and attributes. The nested realm.addClientScope
                // + scope.addProtocolMapper(...) calls pass straight through
                // the IGA wrappers because IGA_REPLAY_ACTIVE is set by replay().
                try {
                    org.keycloak.representations.idm.ClientScopeRepresentation rep =
                            MAPPER.readValue(repJson,
                                    org.keycloak.representations.idm.ClientScopeRepresentation.class);
                    rep.setId(id);
                    if (name != null) rep.setName(name);
                    org.keycloak.models.utils.RepresentationToModel.createClientScope(realm, rep);
                } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
                    throw new RuntimeException(
                            "Failed to deserialize REP_JSON for CREATE_CLIENT_SCOPE replay (CR row id=" + id + ")", e);
                }
            } else {
                // Bare-create safety net for non-REST programmatic callers.
                ClientScopeModel scope = realm.addClientScope(id, name);
                if (scope == null) continue;
                if (protocol != null) scope.setProtocol(protocol);
                if (description != null) scope.setDescription(description);
            }

            if (sig != null && !sig.isEmpty()) {
                em.createQuery("UPDATE ClientScopeEntity e SET e.attestation = :sig WHERE e.id = :id")
                        .setParameter("sig", sig)
                        .setParameter("id", id)
                        .executeUpdate();
            }
        }
    }

    private static void replayUpdateProtocolMapper(KeycloakSession session, RealmModel realm,
                                                    List<Map<String, Object>> rows, String sig, EntityManager em) {
        for (Map<String, Object> row : rows) {
            String mapperId = str(row, "ID");
            if (mapperId == null) continue;
            String clientUuid = str(row, "CLIENT_UUID");
            String clientId = str(row, "CLIENT_ID");
            String scopeId = str(row, "CLIENT_SCOPE_ID");
            org.keycloak.models.ProtocolMapperModel mapper = new org.keycloak.models.ProtocolMapperModel();
            mapper.setId(mapperId);
            mapper.setName(str(row, "NAME"));
            mapper.setProtocol(str(row, "PROTOCOL"));
            mapper.setProtocolMapper(str(row, "PROTOCOL_MAPPER_NAME"));
            Object cfg = row.get("config");
            if (cfg instanceof Map<?, ?> cfgMap) {
                java.util.Map<String, String> config = new java.util.LinkedHashMap<>();
                for (Map.Entry<?, ?> e : cfgMap.entrySet()) {
                    if (e.getKey() != null) {
                        config.put(e.getKey().toString(), e.getValue() == null ? null : e.getValue().toString());
                    }
                }
                mapper.setConfig(config);
            } else {
                mapper.setConfig(new java.util.LinkedHashMap<>());
            }
            if (clientUuid != null || clientId != null) {
                ClientModel client = resolveClient(session, realm, row);
                if (client != null) client.updateProtocolMapper(mapper);
            } else if (scopeId != null) {
                ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
                if (scope != null) scope.updateProtocolMapper(mapper);
            }
            if (sig != null && !sig.isEmpty()) {
                em.createQuery("UPDATE ProtocolMapperEntity e SET e.attestation = :sig WHERE e.id = :id")
                        .setParameter("sig", sig)
                        .setParameter("id", mapperId)
                        .executeUpdate();
            }
        }
    }

    private static void replayRemoveProtocolMapper(KeycloakSession session, RealmModel realm,
                                                    List<Map<String, Object>> rows) {
        for (Map<String, Object> row : rows) {
            String mapperId = str(row, "ID");
            if (mapperId == null) continue;
            String clientUuid = str(row, "CLIENT_UUID");
            String clientId = str(row, "CLIENT_ID");
            String scopeId = str(row, "CLIENT_SCOPE_ID");
            org.keycloak.models.ProtocolMapperModel mapper = new org.keycloak.models.ProtocolMapperModel();
            mapper.setId(mapperId);
            if (clientUuid != null || clientId != null) {
                ClientModel client = resolveClient(session, realm, row);
                if (client != null) client.removeProtocolMapper(mapper);
            } else if (scopeId != null) {
                ClientScopeModel scope = session.clientScopes().getClientScopeById(realm, scopeId);
                if (scope != null) scope.removeProtocolMapper(mapper);
            }
            // No attestation write — the row is being deleted.
        }
    }

    /**
     * Run a JPQL UPDATE that stamps the final attestation on every row of an
     * attribute entity matching (parent_id, name). Multi-value attributes share
     * the (parent_id, name) tuple — every row gets the same attestation.
     */
    private static void stampSigJpql(EntityManager em, String jpql, String sig, String parentId, String name) {
        if (sig == null || sig.isEmpty()) return;
        em.createQuery(jpql)
                .setParameter("sig", sig)
                .setParameter("pid", parentId)
                .setParameter("name", name)
                .executeUpdate();
    }

    // -------------------------------------------------------------------------
    // Utilities
    // -------------------------------------------------------------------------

    private static EntityManager getEm(KeycloakSession session) {
        return session.getProvider(JpaConnectionProvider.class).getEntityManager();
    }

    private static List<Map<String, Object>> parseRows(String rowsJson) {
        try {
            return MAPPER.readValue(rowsJson, LIST_MAP_REF);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse rows JSON", e);
        }
    }

    private static String str(Map<String, Object> row, String key) {
        Object v = row.get(key);
        return v != null ? v.toString() : null;
    }

    /**
     * Resolve a <i>referenced</i> client per the rowsJson key contract:
     * <ol>
     *   <li>{@code CLIENT_UUID} present → {@code getClientById(realm, uuid)}.</li>
     *   <li>else {@code CLIENT_ID} present → {@code getClientByClientId(realm,
     *       humanId)} (CLIENT_ID is the HUMAN identifier, never a UUID).</li>
     * </ol>
     * A UUID is NEVER read out of {@code CLIENT_ID}. No legacy fallback.
     */
    private static ClientModel resolveClient(KeycloakSession session, RealmModel realm,
                                             Map<String, Object> row) {
        String clientUuid = str(row, "CLIENT_UUID");
        if (clientUuid != null) {
            return session.clients().getClientById(realm, clientUuid);
        }
        String clientId = str(row, "CLIENT_ID");
        if (clientId != null) {
            return session.clients().getClientByClientId(realm, clientId);
        }
        return null;
    }

}
